name: rago
channels:
  - nodefaults
  - conda-forge
dependencies:
  - ollama
  - python 3.9.*
  - pip
  - poetry >=2
  - nodejs # used by semantic-release
  - tokenizers
  - compilers
  - pip:
      # distlib issue
      - paginate==0.5.6
      - langdetect
