name: rago
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
  - pip
  - poetry
  - nodejs # used by semantic-release
  - tokenizers
  - pip:
      # distlib issue
      - paginate==0.5.6
      - langdetect
