name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    concurrency:
      group: ci-check-branch-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Check if the PR's branch is updated
        if: ${{ github.event_name == 'pull_request' }}
        uses: osl-incubator/gh-check-pr-is-updated@1.0.0
        with:
          remote_branch: origin/main
          pr_sha: ${{ github.event.pull_request.head.sha }}

  tests:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "macos-latest"]
        build_type: ["cpu", "gpu"]
        exclude:
          - os: macos-latest
            build_type: gpu

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    defaults:
      run:
        shell: bash -l {0}

    concurrency:
      group: ci-tests-${{ matrix.os }}-${{ matrix.python_version }}-${{ matrix.build_type }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      TOKENIZERS_PARALLELISM: false

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda/ci.yaml
          channels: conda-forge,nodefaults
          activate-environment: rago
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "${{ matrix.python_version }}"

      - name: Check Poetry lock
        run: poetry check

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          if [ "${{ matrix.build_type }}" = "gpu" ]; then
            poetry install --with dev --extras "cuda"
          else
            poetry install --with dev
          fi

      - name: Run unit tests (PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: pytest -m "not skip_on_ci" -vvv

      - name: Run unit tests (push)
        if: ${{ github.event_name == 'push' }}
        run: makim tests.unit

      - name: Semantic Release PR Title Check
        uses: osl-incubator/semantic-release-pr-title-check@v1.4.1
        if: success() || failure()
        with:
          convention-name: conventionalcommits

      - name: Setup tmate session
        if: "${{ failure() && (contains(github.event.pull_request.labels.*.name, 'ci:enable-debugging')) }}"
        uses: mxschmitt/action-tmate@v3

  linter:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        shell: bash -l {0}

    concurrency:
      group: ci-linter-docs-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda/ci.yaml
          channels: conda-forge,nodefaults
          activate-environment: rago
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "3.9"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Run style checks
        if: success() || failure()
        run: |
          pre-commit install
          makim tests.linter

      - name: Setup tmate session
        if: "${{ failure() && (contains(github.event.pull_request.labels.*.name, 'ci:enable-debugging')) }}"
        uses: mxschmitt/action-tmate@v3

  install-test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
        install_type: ["default", "cuda"]
        exclude:
          - os: macos
            install_type: cuda # prevent CUDA install on macOS
    name: Install test (${{ matrix.os }} - ${{ matrix.install_type }})

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          if [ "${{ matrix.install_type }}" = "cuda" ]; then
            poetry install --extras "cuda"
          else
            poetry install --extras "cpu"
          fi

      - name: Check torch install
        run: |
          poetry run python -c "import torch; print('Torch version:', torch.__version__); print('CUDA available:', getattr(torch, 'cuda', None) and torch.cuda.is_available())"
